# Generated by Django 4.2.1 on 2023-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('icon', models.ImageField(upload_to='images/icons/', verbose_name='آیکن')),
                ('version', models.CharField(max_length=50, verbose_name='ورژن')),
                ('url', models.URLField(verbose_name='لینک دانلود')),
                ('source', models.URLField(help_text='آدرس سایت', verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'ابزار',
                'verbose_name_plural': 'ابزارها',
            },
        ),
    ]
