# Generated by Django 4.2.1 on 2023-05-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_app', '0015_alter_article_id_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetailPageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='سفارش دهنده')),
                ('image', models.ImageField(upload_to='ads/images/', verbose_name='عکس / گیف')),
                ('url', models.URLField(verbose_name='لینک ارجاع')),
                ('date_start', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('date_end', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to='blog_app.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات صفحه ی مقاله',
            },
        ),
    ]
