# Generated by Django 4.2.1 on 2023-05-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetailpageads',
            name='date_end',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='articledetailpageads',
            name='date_start',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
    ]
