# Generated by Django 4.2.1 on 2023-05-30 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_alter_article_id_post'),
        ('ads_app', '0002_alter_articledetailpageads_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='سفارش دهنده')),
                ('image', models.ImageField(upload_to='ads/images/', verbose_name='عکس / گیف')),
                ('url', models.URLField(verbose_name='لینک ارجاع')),
                ('date_start', models.DateField(verbose_name='تاریخ شروع')),
                ('date_end', models.DateField(verbose_name='تاریخ پایان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات صفحه خانه',
            },
        ),
        migrations.CreateModel(
            name='SearchPageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='سفارش دهنده')),
                ('image', models.ImageField(upload_to='ads/images/', verbose_name='عکس / گیف')),
                ('url', models.URLField(verbose_name='لینک ارجاع')),
                ('date_start', models.DateField(verbose_name='تاریخ شروع')),
                ('date_end', models.DateField(verbose_name='تاریخ پایان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات صفحه جستوجو',
            },
        ),
        migrations.AlterField(
            model_name='articledetailpageads',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
        migrations.CreateModel(
            name='TagPageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='سفارش دهنده')),
                ('image', models.ImageField(upload_to='ads/images/', verbose_name='عکس / گیف')),
                ('url', models.URLField(verbose_name='لینک ارجاع')),
                ('date_start', models.DateField(verbose_name='تاریخ شروع')),
                ('date_end', models.DateField(verbose_name='تاریخ پایان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to='blog_app.tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات صفحه تگ ها',
            },
        ),
        migrations.CreateModel(
            name='CategoryPageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='سفارش دهنده')),
                ('image', models.ImageField(upload_to='ads/images/', verbose_name='عکس / گیف')),
                ('url', models.URLField(verbose_name='لینک ارجاع')),
                ('date_start', models.DateField(verbose_name='تاریخ شروع')),
                ('date_end', models.DateField(verbose_name='تاریخ پایان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to='blog_app.category', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات صفحه دسته بندی ها',
            },
        ),
    ]
