# Generated by Django 4.2.1 on 2023-05-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaerchResault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=50, verbose_name='نام کلید واژه')),
                ('research_count', models.IntegerField(default=0, verbose_name='تعداد دفعات سرچ')),
            ],
            options={
                'verbose_name': 'جستوجو',
                'verbose_name_plural': 'نتیجه جستوجو',
            },
        ),
    ]
