# Generated by Django 4.2.1 on 2023-05-19 12:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.UUIDField(auto_created=True, help_text='دست نزن مَردَک', unique=True, verbose_name='آیدی پست')),
                ('title', models.CharField(max_length=50, verbose_name='* عنوان')),
                ('content', ckeditor.fields.RichTextField(verbose_name='* محتوا')),
                ('image', models.ImageField(upload_to='images/posts/<django.db.models.fields.CharField>/', verbose_name='* تصویر')),
                ('download_help', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='راهنمای دانلود')),
                ('date_created', models.DateTimeField(verbose_name='* تاریخ ایجاد')),
                ('view_visit', models.IntegerField(default=0, editable=False, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='* نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله* ',
                'verbose_name_plural': '* مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='* نام تگ')),
                ('slug', models.SlugField(verbose_name='* اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='* نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='* ایمیل')),
                ('text', models.TextField(verbose_name='* متن نظر')),
                ('date_send', models.DateTimeField(verbose_name='* تاریخ ارسال')),
                ('status', models.BooleanField(verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Downloadbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='* عنوان')),
                ('url', models.URLField(verbose_name='* لینک دانلود فایل')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'باکس دانلود',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='* نام تگ')),
                ('slug', models.SlugField(verbose_name='* اسلاگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='* عنوان')),
                ('image', models.ImageField(upload_to='images/galleries/<django.db.models.fields.related.ForeignKey>/', verbose_name='* تصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.article', verbose_name='* مقاله')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.category', verbose_name='* دسته بندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog_app.tag', verbose_name='* تگ ها'),
        ),
    ]
