# Generated by Django 4.2.1 on 2023-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='id_post',
            field=models.CharField(blank=True, default=949618, help_text='دست نزن مَردَک', max_length=6, null=True, unique=True, verbose_name='آیدی پست'),
        ),
    ]
