# Generated by Django 4.2.1 on 2023-05-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_article_id_post_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.article', verbose_name='* مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadbox',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.article', verbose_name='* مقاله'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='id_post',
            field=models.CharField(blank=True, default='nmiTcnH', help_text='دست نزن مَردَک', max_length=7, null=True, unique=True, verbose_name='آیدی پست'),
        ),
    ]
