# Generated by Django 4.2.1 on 2023-05-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_article_author_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_post',
            field=models.CharField(blank=True, default='1O9OiKX', help_text='دست نزن مَردَک', max_length=7, null=True, unique=True, verbose_name='آیدی پست'),
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='max length: 165 character', max_length=165, verbose_name='Description')),
                ('keywords', models.TextField(help_text='با کاما (,) از هم جدا کنید', verbose_name='Keywords')),
                ('redirect', models.URLField(blank=True, default=None, help_text='میتواند خالی بماند', null=True, verbose_name='Redirect')),
                ('refresh', models.CharField(blank=True, default=None, help_text='e.g: 3;url=https://www.mozilla.org', max_length=100, null=True, verbose_name='Refresh')),
                ('date_created', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپدیت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seo', to='blog_app.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEOs',
            },
        ),
    ]
