# Generated by Django 4.2.1 on 2023-05-20 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0008_alter_article_id_post_alter_seo_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='id_post',
            field=models.CharField(blank=True, default='oB3aQB9', help_text='دست نزن مَردَک', max_length=7, null=True, unique=True, verbose_name='آیدی پست'),
        ),
    ]
