# Generated by Django 4.2.1 on 2023-05-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_article_id_post_alter_seo_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_post',
            field=models.CharField(blank=True, default='fOEzAvm', help_text='دست نزن مَردَک', max_length=7, null=True, unique=True, verbose_name='آیدی پست'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_commnets', to='blog_app.article', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='downloadbox',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_boxs', to='blog_app.article', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='galleris', to='blog_app.article', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/galleries/', verbose_name='تصویر'),
        ),
    ]
