# Generated by Django 4.2.1 on 2023-05-31 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_alter_article_id_post_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_send'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.RemoveField(
            model_name='seo',
            name='redirect',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', help_text='max length: 165 character', max_length=165, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(default='', help_text='با کاما (,) از هم جدا کنید', verbose_name='Keywords'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='', help_text='max length: 165 character', max_length=165, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.TextField(default='', help_text='با کاما (,) از هم جدا کنید', verbose_name='Keywords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='id_post',
            field=models.CharField(blank=True, default='bkvxHyR', help_text='دست نزن مَردَک', max_length=7, null=True, unique=True, verbose_name='آیدی پست'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_comments', to='blog_app.article', verbose_name='مقاله'),
        ),
    ]
