# Generated by Django 4.2 on 2023-06-03 15:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_article_id_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='جواب'),
        ),
    ]
