# Generated by Django 4.2 on 2023-06-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0022_comment_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='blog_app.article', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='downloadbox',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_boxs', to='blog_app.article', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='blog_app.article', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='blog_app.article', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='SEO نویسنده'),
        ),
    ]
