# Generated by Django 4.2 on 2023-06-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='settings_app.setting', verbose_name='تنظیم'),
        ),
    ]
