# Generated by Django 4.2.1 on 2023-06-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=50, verbose_name='عنوان تماس'),
            preserve_default=False,
        ),
    ]
