# Generated by Django 4.2.1 on 2023-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='خواندن'),
        ),
    ]
